---
title: Peppe Móveis Planejados
timezone: America/Sao_Paulo
collections:
  categorias:
    title: Categorias
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: categorias
  values:
    image: 
description: 'Criamos um Projeto em 3D personalizado da sua casa ou  empresa seguindo
  as suas orientações e o seu estilo.

'
tel:
  number: "+5513981101762"
  label: "(13) 98110-1762"
email: novacasaplanejada@gmail.com
baseurl: ''
url: https://peppemoveisplanejados.com.br
markdown: kramdown
permalink: pretty/
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
